# Generated by Django 4.2.4 on 2023-08-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_likes_alter_post_category_alter_post_user_short_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_images/', verbose_name='Photo'),
        ),
    ]
