# Generated by Django 4.2.4 on 2023-08-15 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_profile_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='short',
            options={'verbose_name': 'Short', 'verbose_name_plural': 'Shorts'},
        ),
    ]
